### ISSUE TITLE
Error Installing: ffi (1.9.14)

### ISSUE THREAD

**Issue by roberttolton** [emyl/vagrant-triggers#71]
I'm getting the following error when trying to install?
```
An error occurred while installing ffi (1.9.14), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.14'` succeeds before bundling.
```
I ran `gem install ffi -v '1.9.14'` but it didn't help.

Max OS X El Capitan, latest Vagrant

Any ideas?

**Comment by emyl** [comment]
Hi,

Code that handles plugin installation comes from upstream, I think you could take a look to these similar issues:

https://github.com/mitchellh/vagrant/issues/6045
https://groups.google.com/forum/#!topic/vagrant-up/rh19VUBBdek
https://github.com/devopsgroup-io/vagrant-hostmanager/issues/140

I'm going to close the issue since I think there's nothing I can do, feel free to reopen it if you think otherwise.
